### ISSUE TITLE
Do we need input layers copied into every BRAT project?

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/sqlBRAT#18]
@joewheaton and @wally-mac  do we really need the input layers (DEM, slope drainage area raster, veg, NHD) copied into every single BRAT project? In the North American context we are always going to have a riverscapes context project that can be used in RAVE in conjunction with the BRAT results:

![Screen Shot 2020-02-25 at 12 36 57 PM](https://user-images.githubusercontent.com/8645379/75285466-889a1b80-57cb-11ea-9600-68b2420453b4.png)

If we duplicate the riverscape context layers in the BRAT project then each BRAT project is about 400Mb. If we exclude them and instead rely on the riverscapes context project then each BRAT project becomes about 40Mb and still every output layer can be displayed in RAVE.

**Comment by joewheaton** [comment]
Well... "it depends". What do you mean by inputs copied into every project?  If what you're asking me is the input context (i.e. access to display those layers in web map or in RAVe) important, and the only way you let me do that is having it in my BRAT riverscapes project, then YES! I need it and I don't care how big the file is. However, if you take my _many_ previous suggestions that a Riverscapes Project input always needs an entry, but doesn't need to live in the project or be exported in a specific output (i.e. zip file of that) then many options come to mind. You seem to be most concerned about sending around a zip file. Lets back up to the premises of context, transparency and reproducability. These can be achieved by:

- Having a reference to a path in a Riverscapes Context Project that is also hosted locally
- Having a reference to a path in a Riverscapes Context Project that is hosted in a Warehouse and those layers are tiled so they can be added via RAVE (e.g. as WMTS)... what I want as user is context and to see them.
- Having a reference (in case of NED DEM, LANDFIRE, NHD, TIGER) to the very WMTS or USGS/NOAA interfaces you downloaded these from so they can be displayed for context.
- Not shipping files of inputs or intermediates that are guranteed to be able to be reproducibile (e.g. project may not have them, but could know what they are and if requested, go get them from a warehouse or reproduce them (in case of within a model like GCD)...

There are lots of ways to do this, but if all you're complaining about file size, I say tough luck (I don't care). To do what I said above requires more development, but does have major performance and filesize gains.

**Comment by joewheaton** [comment]
Hey another thought for you... I can dig it up in BRAT stuff. Let me add those context layers easily with button for context....

**Comment by philipbaileynar** [comment]
Closing this issue. RAVE is demonstrating the value of having all the layers in BRAT. Once things quieten down we can perhaps pursue using references to the riverscapes context projects instead. But I think this should be punted down the road until desktop RAVE has download capability (i.e. it can resolve references). Closing for now. Reopen if this becomes a priority.
