### ISSUE TITLE
BRAT Run needs to update project.rs.xml

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/sqlBRAT#21]
we need the project file to change because this is how the warehouse knows there has been activity. 

I suggest we add as much MetaData as is useful. Anything you'd conceivably want to know from the web interface.

* Date Run
* Time taken
* Any special warnings or messages (not sure about this one)
* .... etc

This is likely going to need an argparse parameter so we can find the project file (maybe an optional one in case we don't have a project?)

Let @MattReimer know when this is done because it will affect the automation scripts.

**Comment by MattReimer** [comment]
huh. Looks like I started work on this already. Must have done it in my sleep. 

Feel free to do it differently.

https://github.com/Riverscapes/sqlBRAT/blob/master/brat_run.py#L169

**Comment by philipbaileynar** [comment]
@MattReimer what's the status on this please?

**Comment by MattReimer** [comment]
```
BRATRunVersion
BRATRunTimestamp
```

these have been added. the main task was to get brat_run aware of the xml file. This proved harder than I thought. related to #37
