### ISSUE TITLE
Flow accumulation layer not accounting for upstream contributing area outside of HUC8

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/sqlBRAT#23]
From @sshahverdian and moved here from: [RAVE](https://github.com/Riverscapes/RaveAddIn/issues/17): 
> The Problem
Data set: MiddleBear (ID) HUC8 16010202 RSContext. The flow accumulation layer does not account for upstream contributing area outside of the HUC8 boundary. The result is that portions of the mainstem Bear river which should have a very large contributing area are identified as having very small contributing areas. It appears that in order to accurately capture the flow accumulation values, other HUC8s would need to be integrated for this specific output.

**Comment by joewheaton** [comment]
Excellent catch @sshahverdian. This is something that @wally-mac and crew figured out a fix for in [PyBRAT (raised in Issue 19)](https://github.com/Riverscapes/pyBRAT/issues/19). @philipbaileynar can you look at pyBRAT to see what Bangen did to [fix this]( https://github.com/Riverscapes/pyBRAT/commit/38b103fd5ae1246f07e919cfeba776c6a5c2f7f4) and as ask @wally-mac if you have any questions. 

I think that @philipbaileynar is less concerned about this as he no longer uses flow accumulation in sqlBRAT for his stream power estimates. However, this needs to be fixed because:
- flow accumulation is and will be used in lots of other models (including BRAT when run without NHD+ HR)
- All intermediates should be correct.

**Comment by philipbaileynar** [comment]
@sshahverdian are you trying to display the catchment area cartographically or simply calculate total drainage area for each reach?

Note that the riverscapes context project uses NHDPlusHR which comes with total drainage area pre-calculated. See the TotDASqKm field in the NHD flow lines ShapeFile.

**Comment by joewheaton** [comment]
@philipbaileynar I hear you on:

> Note that the riverscapes context project uses NHDPlusHR which comes with total drainage area pre-calculated. See the TotDASqKm field in the NHD flow lines ShapeFile.

But that is too narrow a use case. Anything we have should be correct and the more generic implementation of sqlBRAT and other models will need this (i.e. becuuse they don't have NHD PlusHR, or even if they do we move it OFF the line. 

 However, this needs to be fixed because:

>- flow accumulation is and will be used in lots of other models (including BRAT when run without NHD+ HR)
>- All intermediates should be correct.

**Comment by philipbaileynar** [comment]
This requires a voice conversation. There are too many ideas racing around.

**Comment by philipbaileynar** [comment]
I'm closing this issue. HND Plus HR has the correct total drainage area attribute for each reach that does indeed account for upstream flow area (upstream of the HUC in question).

We do also include a drainage area raster for Riverscapes Context, VBET and BRAT projects although it is never used for calculations.
