### ISSUE TITLE
Include HUC10 and HUC12 with hydrology

### ISSUE THREAD

**Issue by sshahverdian** [Riverscapes/sqlBRAT#24]
## The Problem
The hydrology folder in a RS context project has the watershed boundaries for HUC2 - HUC8. It would be useful to also have the HUC10 and HUC12 for cartography purposes, and to use as a mask to clip the HUC8 rasters to make processing times faster when in Arc, rather than loading the HUC8 data for any/all processes.

**Comment by philipbaileynar** [comment]
@sshahverdian I have re-run the riverscapes context project for 16010202 and it now includes HUC10 and HUC12 boundaries. Please download the latest copy and let me know if this works for you.

Note that while the project contains the new ShapeFiles, they won't be visible in the RAVE project explorer yet. You will need to add them manually using ArcCatalog or "Add to Map" button in ArcGIS.

**Comment by sshahverdian** [comment]
@philipbaileynar Got it. Thanks.
