### ISSUE TITLE
Test new hydrologic equations for 16010202

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/sqlBRAT#26]
@MattReimer can you please test the following hydrologic equations work in BRAT Build and BRAT Run for HUC 16010202. This is the only HUC that needs to be run. The Riverscapes Context project has already been run and is stored in the Anabranch program in the data warehouse. You do **not** need to upload the BRAT project when you are done. Just confirm that the equations, values and units below all work with our code. When you are done, please leave git and the spreadsheet in such a way that I can pull and run the HUC myself on my local system.

I have already put the following hydrologic formulas in the Google sheet. Note how they use different parameters than those in our BRAT database lookup table. I'm unsure how to handle this. We might just want to add some new parameters for now if needed.

**QLow**
`0.0247 * (DAsqm**1.05) * (E**-3.86) * (F**-0.947) * (P**3.99)`

**Q2**
`0.00557 * (DAsqm**0.754) * (P**2.34)`

But here's the important part!!!!!!!!!!!!!!!! These formulas use the following definitions and I'm unsure if the units match those used in our code.

DAsqm | Drainage area (square miles)
-- | --
P | mean annual precipitation (inches)
F | Percent of drainage basin with forest land cover
Emin | Minimum elevation in basin (feet)

Here are the parameters for 16010202:

NAME | HUC 8 CODE | Code Region | BR (Basin Relief) | P (Mean Annual Precipitation - mm) | P (Mean Annual Precipitation - in) | E (Mean Basin Elevation - meters) | E (Mean Basin Elevation - feet) | E_min (Minimum elevation - meters) | E_min (Minimum elevation - feet) | F (% of basin area with forest cover) | F + 1 | S30 (% of area with slope >30%) | S30 + 1 | BS_deg (average basin slope in degrees) | BS_pct (average basin slope in percent) | Notes |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
MiddleBear | 16010202 | 18 | 5617 | 553 | 21.77 | 1735 | 5693 | 1329 | 4360 | 17.31 | 18.31 | NA | NA | 11.28 | NA |   |   |   |   |   |   |   |   |   |   |   |

**Comment by MattReimer** [comment]
* `DAsqm` is the right unit
* F === FOREST I think and that's just a percentage so it should be fine??
* but `P` and `E` will need a conversion. 

P and E get converted in the software so my suggestion would be to add another conversion factor to the equation

Something like

```
0.0247 * (DAsqm**1.05) * (E**-3.86) * (F**-0.947) * (P**3.99)

0.0247 * (DRNAREA**1.05) * ((ELEV/3.28084)**-3.86) * (FOREST**-0.947) * ((PRECIP/0.0393701)**3.99)

and

0.0247 * (DAsqm**1.05) * ((ELEV/3.28084)**-3.86) * (FOREST**-0.947) * ((PRECIP/0.0393701)**3.99)
``` 

I need to double check those conversions but you get the idea.

**Comment by MattReimer** [comment]
There doesn't seem to be anywhere I can find where the units for these parameters are docu

**Comment by MattReimer** [comment]
THis was just for last friday. Closing it.
