### ISSUE TITLE
RS Context Question - Ecoregions

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/sqlBRAT#29]
In the National Dataset there are USA Ecoregions are in there.  Can these added to the Riverscapes Context for the watershed please?

**Comment by MattReimer** [comment]
I'm not going to clip this. Just filter them using attributes.

**Comment by MattReimer** [comment]
Ok. Couple of things to take note of here:

1. Had to reproject the ecoregions shapefile to WGS84 `NationalDatasets/ecoregions/us_eco_l3_state_boundaries.shp`

@philipbaileynar the national project has changed. A new zip is being rebuilt as we speak but it might take 15-20 minutes. You'll need the new ecoregions shapefile 

2. `rs_context` now takes a new ecoregions parameter. Update your scripts accordingly. 

Here's some visual confirmation that it worked:
```
Pink = HUC boundary
Yellow = Ecoregions original file
Blue = Clipped ecoregions file
```
<img width="821" alt="Screen Shot 2020-06-05 at 12 48 19 PM" src="https://user-images.githubusercontent.com/1063391/83917995-b547c280-a72c-11ea-88a8-b21bcadba5be.png">

**Comment by joewheaton** [comment]
@philipbaileynar when this update is pushed to over-riden RS_Context projects, please task @Cashe93 with coming up with some ecoregion symbology layer files (should match below) and business logic in RS_Context. Nice one.

![image](https://user-images.githubusercontent.com/9723905/83933293-8f3e1480-a764-11ea-8fdc-7c3d23830322.png)
