### ISSUE TITLE
Unnecessary vegetation overrides

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/sqlBRAT#39]
Someone has added several vegetation overrides into the database that are exactly the same as the defaults. These don't need to be in the database and can be deleted.

@mhallerud did you enter these or was it Geoff?

<img width="963" alt="Screen Shot 2020-05-22 at 8 27 34 PM" src="https://user-images.githubusercontent.com/8645379/82720698-d14a5f00-9c6a-11ea-8c72-93fde29d0ef3.png">

**Comment by mhallerud** [comment]
@philipbaileynar I only changed values for the Middle Bear (associated with the Northern Basin and Range ecoregion), so it must have been Geoff.

**Comment by philipbaileynar** [comment]
Closing this issue because it doesn't affect the performance of the model. I just wanted clarification. Thanks.
