### ISSUE TITLE
Incorporate TNMFRC NTD attribute

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/sqlBRAT#43]
Make sure that brat is copying over the `TNMFRC` attribute when building the riverscapes context transportation layer. 

The goal is to retain this field from the original National Transportation Dataset download and carry it forward into both Riverscapes Context and BRAT projects. This field is the key attribute used to symbolize different road types in RAVE.

**Comment by MattReimer** [comment]
e098ab8 fixes this
