### ISSUE TITLE
LandFire Vegetation Attribute Table

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/sqlBRAT#45]
We need to include in the National Project a raster attribute table (VAT) for both the historical and existing vegetation rasters. This value attribute table needs to then get include in both the riverscapes context and BRAT projects. These VAT are vital for appropriate symbology in RAVE.

pyBRAT used these VAT for additional fields used during model calculations. For example vegetation suitability was stored as a column in these VAT. We don't need this capability because sqlBRAT stores all suitability in the SQLite database. We are also now [producing vegetation suitability rasters](https://github.com/Riverscapes/sqlBRAT/issues/31) with each model run.

So I confess that I don't know how to tackle this issue. ESRI has [documentation on raster VAT](https://desktop.arcgis.com/en/arcmap/10.3/manage-data/raster-and-images/raster-dataset-attribute-tables.htm). My hope is that if we generate VAT in the national project then GDAL will do the right thing and copy them along with the raster into the riverscapes context project.

Here's some [documentation on the LandFire 2.0.0 classification](https://www.landfire.gov/evt.php).

**Comment by MattReimer** [comment]
@philipbaileynar please attach CSV files and I'll take a look.

**Comment by philipbaileynar** [comment]
BTW @MattReimer this post looks useful

https://gis.stackexchange.com/questions/40958/python-gdal-and-building-raster-attribute-tables

**Comment by philipbaileynar** [comment]
I have put copies of the two VAT on the NAR Drive at:

```
Projects\BRAT\LandFire
```

**Comment by MattReimer** [comment]
The National project has been augmented with RAT Tables. Despite being tricky to create a RATtable is just a sidecar file `FILENAME.tiff.aux.xml`

which looks something like this:

``` xml
<PAMDataset>
  <PAMRasterBand band="1">
    <GDALRasterAttributeTable tableType="thematic">
      <FieldDefn index="0">
        <Name>Value</Name>
        <Type>0</Type>
        <Usage>0</Usage>
      </FieldDefn>
      <FieldDefn index="1">
        <Name>Count</Name>
        <Type>1</Type>
        <Usage>0</Usage>
      </FieldDefn>
      <FieldDefn index="2">
        <Name>EVT_Name</Name>
        <Type>2</Type>
        <Usage>0</Usage>
      </FieldDefn>
      <FieldDefn index="3">
        <Name>LFRDB</Name>
        <Type>0</Type>
        <Usage>0</Usage>
      </FieldDefn>
      <FieldDefn index="4">
```

unfortunately QGIS isn't really set up to read the RAT table so we'll need to verify it in ESRI.

**Comment by philipbaileynar** [comment]
Is there any functional difference between XML and dbf value attribute tables?

Does GDAL copy these files by default or do we need to manually move them around?

**Comment by MattReimer** [comment]
I'm putting this here because the documentation about it is terrible and I got tired of trying to find it every time:

### RAT Column types

```
    GFT_Integer = _gdalconst.GFT_Integer
    GFT_Real = _gdalconst.GFT_Real
    GFT_String = _gdalconst.GFT_String
```

### RAT Column Usages

```
        GFU_Generic = _gdalconst.GFU_Generic
 	GFU_PixelCount = _gdalconst.GFU_PixelCount
 	GFU_Name = _gdalconst.GFU_Name
 	GFU_Min = _gdalconst.GFU_Min
 	GFU_Max = _gdalconst.GFU_Max
 	GFU_MinMax = _gdalconst.GFU_MinMax
 	GFU_Red = _gdalconst.GFU_Red
 	GFU_Green = _gdalconst.GFU_Green
 	GFU_Blue = _gdalconst.GFU_Blue
 	GFU_Alpha = _gdalconst.GFU_Alpha
 	GFU_RedMin = _gdalconst.GFU_RedMin
 	GFU_GreenMin = _gdalconst.GFU_GreenMin
 	GFU_BlueMin = _gdalconst.GFU_BlueMin
 	GFU_AlphaMin = _gdalconst.GFU_AlphaMin
 	GFU_RedMax = _gdalconst.GFU_RedMax
 	GFU_GreenMax = _gdalconst.GFU_GreenMax
 	GFU_BlueMax = _gdalconst.GFU_BlueMax
 	GFU_AlphaMax = _gdalconst.GFU_AlphaMax
 	GFU_MaxCount = _gdalconst.GFU_MaxCount
```

**Comment by philipbaileynar** [comment]
@wally-mac can you please review this screenshot and confirm if it looks "right".

What follows is the LandFire 2.0.0 EVT raster with a new Raster Attribute TAble (RAT) that @MattReimer built. It's similar to the raster DBF files that USU has used in the past, but this version is actually XML. It's a sidecar file, so it simply sits next to the TIF file and has the same file name but with the suffix `*.aux.xml`.

@wally-mac can you confirm two things:

1. The names showing up are what a BRAT analyst would want to see when exploring vegetation during BRAT calibration/verification? i.e. @mhallerud showed me how she zooms in on the network and reviews the types of vegetation adjacent to the NHD network and then assigns the suitability values this way. Please confirm that the screenshot is the appropriate classification that you would use for this process.
1. Is the symbology correct? Are these the "official" LandFire red/green/blue values that you are familiar with? (We didn't choose these. They came along for the ride from the DBF that we used to generate the RAT XML).

Let me know if you would like a screenshot of a different spatial extent. Alternatively I can provide instructions on how to download the necessary files for you to play with.

<img width="1540" alt="Screen Shot 2020-06-05 at 10 06 17 AM" src="https://user-images.githubusercontent.com/8645379/83908218-92f97900-a71b-11ea-8752-154d13c0018a.png">

**Comment by wally-mac** [comment]
@philipbaileynar just taking a quick look at the screen shot and one thing that jumps out at this scale is the amount of white cells (i.e non-classified landcover). I don't know if this is an error or not but I'm just surprised to see that much of it. Is this something you and @MattReimer could verify? Otherwise, looking at the symbology it appears to be the same we've used for our vegetation raster.  Nice work, this will be a very useful product. Thanks!

**Comment by philipbaileynar** [comment]
My bad @wally-mac . I provided @MattReimer with an incomplete lookup table. I'm working on providing @MattReimer  with a complete lookup file now.

**Comment by philipbaileynar** [comment]
@wally-mac I cannot find a complete LandFire 2.0.0 EVT lookup table. The web site is terrible. Do you have a copy please? Any format would do. CSV, DBF, XML...

**Comment by wally-mac** [comment]
@philipbaileynar [here](https://usu.box.com/s/2qg797b7uw7ber1vw8y8d3cxqpcbiznw) is a link to the landfire 2.0.0 EVT DBF file that I found on box for the Idaho BRAT project.  I'm not sure if this will have all the landcover classes for the western US or not.

**Comment by philipbaileynar** [comment]
@MattReimer I just ran the latest version of BRAT build and BRAT run. I did not get RATs next to the veg rasters in the BRAT inputs folder:

<img width="245" alt="Screen Shot 2020-06-09 at 9 32 37 AM" src="https://user-images.githubusercontent.com/8645379/84174984-2987ac00-aa34-11ea-90f3-798b27c438a8.png">

**Comment by MattReimer** [comment]
Did you verify that RAT was there next to the original rasters in the NationalProject? 

gdalWarp should copy the xmls over. There were no issues when I did it.

**Comment by philipbaileynar** [comment]
My bad...

**Comment by philipbaileynar** [comment]
@MattReimer I can confirm that the RATs got created in the BRAT project as part of BRAT build. Thanks.

**Comment by philipbaileynar** [comment]
Here is a web page that lists all the CSVs for various LandFire datasets. This was incredibly difficult to find!

https://www.landfire.gov/library_list.php?cat=1

I have also attached a zip containing the two vegetation type CSV files from this site that we need. It also contains the older Landfire 1.4.0 information too. But sqlBRAT only uses LandFire 2.0.0

* LandFire 2.0.0 Existing Vegetation Type (EVT)
* LandFire 2.0.0 Biophysical Settings (BPS)

[Landfire_LookupTables.zip](https://github.com/Riverscapes/sqlBRAT/files/4768701/Landfire_LookupTables.zip)

@MattReimer you should be able to create complete RATs for both datasets using these files.

**Comment by MattReimer** [comment]
Wow. I even looked a bit myself and I wasn't able to find them

All 4 rasters have had their RATs updated. The ZIP file is building as we speak.
