### ISSUE TITLE
Risk and Undesirable Dams 

### ISSUE THREAD

**Issue by Cashe93** [Riverscapes/sqlBRAT#46]
The output for Risk and Undesirable Dams field appears to be invalid 

[pyBRAT]
![pyBRAT](https://user-images.githubusercontent.com/49880208/83468051-ea0bff00-a438-11ea-92f9-95a35e727cd1.png)

[sqlBRAT]
<img width="1196" alt="sqlBRAT" src="https://user-images.githubusercontent.com/49880208/83468053-eaa49580-a438-11ea-945f-f9feaf83f5e8.png">

**Comment by philipbaileynar** [comment]
The good news is that there was a really simple bug that was mixing up risk and opportunity calculations. This was quick to fix. Now we are getting more varied results (see below).

This has highlighted a different problem that reaches with zero discharge (see canals in the central flat valley floor) are getting skipped during several processes. They end up with several zero values in the attribute table. In the case of Risk these zero drainage reaches get no Risk value in SQLite and therefore no string value in the `oPBRC_CR` attribute. The reaches appear omitted from the risk map. I will log this as a separate issue.

<img width="819" alt="Screen Shot 2020-06-10 at 4 07 04 PM" src="https://user-images.githubusercontent.com/8645379/84328370-a13dff80-ab36-11ea-8cc0-fe4051f09bda.png">

**Comment by philipbaileynar** [comment]
I just overrode all NULL drainage area values with zero and now get this for risk:

<img width="477" alt="Screen Shot 2020-06-10 at 8 17 35 PM" src="https://user-images.githubusercontent.com/8645379/84341251-85972100-ab57-11ea-844f-0b727478224d.png">
