### ISSUE TITLE
Historic Vegetation Raster is broken in some watersheds

### ISSUE THREAD

**Issue by tyler1218hatch** [Riverscapes/sqlBRAT#58]
In HUC 14050001, the historic vegetation raster does not appear on the map, and is somehow missing all of its data. This results in many other effects, such as all Historic dam capacity and size being estimated as zero. This also affects all iterations of the raster, such as suitability.

![image](https://user-images.githubusercontent.com/27084463/86300618-0f6f6280-bbc9-11ea-8cc0-11940d4b5887.png)
![image](https://user-images.githubusercontent.com/27084463/86300629-139b8000-bbc9-11ea-9386-fc2352856469.png)

**Comment by philipbaileynar** [comment]
@tyler1218hatch increased the historic veg raster to cover the watersheds that we will run most often. This should be fixed now. We also write -1 for invalid fields, making it easier to spot problems.
