### ISSUE TITLE
Converting LANDFIRE 1.4.0 to 2.0.0: Mismatches need to be fixed.

### ISSUE THREAD

**Issue by tyler1218hatch** [Riverscapes/sqlBRAT#63]
There are 9 vegetation IDs where the +4000 crosswalk between 1.4.0 and 2.0.0 yields different names. We need to go through each of these and decide if they are actually the same thing. or if they should be considered different. 

If we believe that the old name and new name are actually the same, we can just take the old suitability value and make that the new default. If they are meaningfully different, we need to create a new suitability score.

Veg ID | LANDFIRE 1.4.0 Name | LANDFIRE 2.0.0 Name
-- | -- | --
7200 | [Coastal Douglas-fir Woodland] | [Recently Disturbed Other-Tree Cover]
7234 | [Mesic Montane Douglas-fir Forest] | [Mediterranean California Mesic Serpentine Chaparral]
7940 | [Western Cool Temperate Undeveloped Ruderal Deciduous Forest] | [Western Cool Temperate Developed Ruderal Deciduous Forested Wetland]
7941 | [Western Cool Temperate Undeveloped Ruderal Evergreen Forest] | [Western Cool Temperate Developed Ruderal Evergreen Forested Wetland]
7157 | [North Pacific Swamp Systems] | [North Pacific Lowland Riparian Shrubland]
7159 | [Rocky Mountain Montane Riparian Forest and Woodland] | [North Pacific Montane Riparian Shrubland]
7941 | [Western Cool Temperate Undeveloped Ruderal Evergreen Forest] | [Western Cool Temperate Developed Ruderal Evergreen Forested Wetland]
7943 | [Western Cool Temperate Undeveloped Ruderal Shrubland] | [Western Cool Temperate Developed Ruderal Shrub Wetland]
7944 | [Western Cool Temperate Undeveloped Ruderal Grassland] | [Western Cool Temperate Developed Ruderal Herbaceous Wetland]

If @philipbaileynar or @wally-mac could look through these and decide if they should be considered the same or different, that would be great.

**Comment by wally-mac** [comment]
@tyler1218hatch Thank you for making a table of the 9 vegetation IDs where the +4000 crosswalk between 1.4.0 and 2.0.0 yields different names. I think that all 9 of them should be considered different.

**Comment by tyler1218hatch** [comment]
@wally-mac Sounds good. Looking at the LANDFIRE 2.0.0 values, 6 of them already have defaults, while 3 did not (bold and italicized). Please look over these suitabilities (especially the bold ones, which I assigned a suitability to), and let me know if they look good. If so, I'll add them to the sheet. Thanks!

Veg ID | LANDFIRE 2.0.0 Name |  Proposed Suitability
-- | -- | --
7200 | [Recently Disturbed Other-Tree Cover] | 1
7234 | [Mediterranean California Mesic Serpentine Chaparral] | _**1**_
7940 | [Western Cool Temperate Developed Ruderal Deciduous Forested Wetland] | _**3**_
7941 | [Western Cool Temperate Developed Ruderal Evergreen Forested Wetland] | 3
7157 | [North Pacific Lowland Riparian Shrubland] | _**4**_
7159 | [North Pacific Montane Riparian Shrubland] | 4
7941 | [Western Cool Temperate Developed Ruderal Evergreen Forested Wetland] | 3
7943 | [Western Cool Temperate Developed Ruderal Shrub Wetland] | 3
7944 | [Western Cool Temperate Developed Ruderal Herbaceous Wetland] | 3

**Comment by philipbaileynar** [comment]
@tyler1218hatch I don't see your 4th July vegetation suitability values in git. Have you implemented these changes in the Google Sheet?

**Comment by tyler1218hatch** [comment]
@philipbaileynar They're in there now. Should this issue be closed?

**Comment by philipbaileynar** [comment]
Thanks @tyler1218hatch these will get picked up next time @MattReimer runs the automation.
