### ISSUE TITLE
Converting LANDFIRE 1.4.0 to 2.0.0: Some converted values are absent from the Google Sheet

### ISSUE THREAD

**Issue by tyler1218hatch** [Riverscapes/sqlBRAT#64]
There are 22 vegetation IDs where the +4000 crosswalk between 1.4.0 and 2.0.0 yields a Vegetation ID that doesn't exist within the Google Sheet. For each of these, we need to decide if they should be added into the google sheet, or just not included. It's possible that these values don't exist in LANDFIRE 2.0.0, so there's no reason to add suitabilites if those values will never appear.

LANDFIRE 1.4.0   Conversion | Class Name | Epoch | Suitability
-- | -- | -- | --
7001 | Inter-Mountain Basins Sparsely Vegetated Systems | Landfire 2.0.0 EVT | 0
7003 | North Pacific Sparsely Vegetated Systems | Landfire 2.0.0 EVT | 0
7004 | North American Warm Desert Sparsely Vegetated Systems | Landfire 2.0.0 EVT | 0
7006 | Rocky Mountain Alpine/Montane Sparsely Vegetated Systems | Landfire 2.0.0 EVT | 0
7154 | Inter-Mountain Basins Montane Riparian Forest and Woodland | Landfire 2.0.0 EVT | 4
7160 | Rocky Mountain Subalpine/Upper Montane Riparian Forest and Woodland | Landfire 2.0.0 EVT | 2
7164 | Rocky Mountain Wetland-Herbaceous | Landfire 2.0.0 EVT | 1
7181 | Introduced Upland Vegetation-Annual Grassland | Landfire 2.0.0 EVT | 1
7182 | Introduced Upland Vegetation-Perennial Grassland and Forbland | Landfire 2.0.0 EVT | 1
7183 | Introduced Upland Vegetation-Annual and Biennial Forbland | Landfire 2.0.0 EVT | 1
7186 | Introduced Upland Vegetation-Shrub | Landfire 2.0.0 EVT | 1
7220 | Artemisia tridentata ssp. vaseyana Shrubland Alliance | Landfire 2.0.0 EVT | 1
7227 | Dry-mesic Montane Douglas-fir Forest | Landfire 2.0.0 EVT | 2
7232 | Abies grandis Forest Forest | Landfire 2.0.0 EVT | 2
7233 | Subalpine Douglas-fir Forest | Landfire 2.0.0 EVT | 2
7235 | Xeric Montane Douglas-fir Forest | Landfire 2.0.0 EVT | 2
7251 | Rocky Mountain Montane Riparian Shrubland | Landfire 2.0.0 EVT | 4
7252 | Rocky Mountain Subalpine/Upper Montane Riparian Shrubland | Landfire 2.0.0 EVT | 3
7255 | Inter-Mountain Basins Montane Riparian Shrubland | Landfire 2.0.0 EVT | 4
7266 | Oregon White Oak Woodland | Landfire 2.0.0 EVT | 2
7267 | Douglas-fir - Oregon White Oak Woodland | Landfire 2.0.0 EVT | 2
7294 | Barren | Landfire 2.0.0 EVT | 0

If @philipbaileynar  or @wally-mac could look through these and decide if they should be considered the same or different, that would be great.

**Comment by wally-mac** [comment]
@tyler1218hatch thank you for generating this table of the 22 vegetation IDs where the +4000 crosswalk between 1.4.0 and 2.0.0 yields a Vegetation ID that doesn't exist within the Google Sheet. I believe they  should be added into the google sheet,  If it ends up that these values don't exist in LANDFIRE 2.0.0, they could be removed later.

**Comment by tyler1218hatch** [comment]
@wally-mac Sounds good. I agree that this seems like the most sensible action. 

@philipbaileynar I don't have permission to add new rows to the VegetationTypes tab. Could you either give me the correct permissions, or add them yourself? They should be formatted so that it is a single copy paste.

**Comment by philipbaileynar** [comment]
The vegetation type IDs @tyler1218hatch lists above do not exist within LandFire 2.0.0. They do not exist in the lookup data or the raster itself. This leads me to suspect that these vegetation types have either been deprecated or rolled into other classes.

@tyler1218hatch can you please pick one or two of the classes above and find some locations where they exist in LandFire 1.4 and then verify what these areas are coded as in LandFire 2.0.0. i.e. just find some pixels of "Oregon White Oak Woodland" in LandFire 1.4 then use ArcGIS Identify tool to discover what the corresponding pixels are in LandFire 2.0.0.

You can get both EVT rasters from the Data Warehouse in the **CRB Program**. Look in the **National Project**. Don't download the entire project because it's many many Gb. Instead, expand the project details and download just the two EVT rasters that you need. Shout if you need further instructions.

**Comment by tyler1218hatch** [comment]
@philipbaileynar I looked at which changes from 1.4.0 to 2.0.0 were most common in these specific vegetation values. 

Old Value (That doesn't exist in 2.0.0)| What it most commonly changed to
-- | --
Dry-mesic   Montane Douglas-fir Forest | Northern Rocky Mountain Dry-Mesic Montane   Mixed Conifer Forest
Abies grandis Forest Forest | Northern Rocky Mountain Dry-Mesic Montane Mixed Conifer Forest
Introduced Upland   Vegetation-Annual Grassland | Inter-Mountain Basins Big Sagebrush Steppe
Introduced Upland   Vegetation-Annual Grassland | Inter-Mountain Basins Big Sagebrush Shrubland
Dry-mesic Montane Douglas-fir   Forest | Northern Rocky Mountain Ponderosa Pine Woodland and Savanna
Introduced Upland   Vegetation-Annual Grassland | Great Basin & Intermountain Ruderal Shrubland
Introduced Upland   Vegetation-Annual Grassland | Columbia Plateau Steppe and Grassland
Rocky Mountain   Wetland-Herbaceous | Rocky Mountain Alpine-Montane Wet Meadow
Rocky Mountain Subalpine/Upper   Montane Riparian Forest and Woodland | Northern Rocky Mountain Dry-Mesic Montane Mixed Conifer Forest

Overall, I don;t think there's a ton to worry about. We've shown that suitability didn't change that much between 1.4.0 and 2.0.0. I think that these are classes that LANDFIRE just got rid of and recoded those regions.

**Comment by philipbaileynar** [comment]
That looks good @tyler1218hatch . At the risk of dragging this out further... do the LandFire 2.0.0 types that "these are commonly changed to", do they all have the appropriate suitabilities?

So you originally had "Dry-mesic Montane Douglas-fir Forest" needing a suitability of 2. Can you confirm if the "Northern Rocky Mountain Ponderosa Pine Woodland" has the value of 2.

Does it make sense what I'm asking?

**Comment by tyler1218hatch** [comment]
Old   Value (That doesn't exist in 2.0.0) | Old Suitability | What it most commonly changed to | New Suitability
-- | -- | -- | --
Dry-mesic   Montane Douglas-fir Forest | 2 | Northern Rocky Mountain   Dry-Mesic Montane Mixed Conifer Forest | 2
Abies   grandis Forest Forest | 2 | Northern Rocky Mountain   Dry-Mesic Montane Mixed Conifer Forest | 2
Introduced   Upland Vegetation-Annual Grassland | 1 | Inter-Mountain Basins Big   Sagebrush Steppe | 0
Introduced   Upland Vegetation-Annual Grassland | 1 | Inter-Mountain Basins Big   Sagebrush Shrubland | 2
Dry-mesic   Montane Douglas-fir Forest | 2 | Northern Rocky Mountain   Ponderosa Pine Woodland and Savanna | 2
Introduced   Upland Vegetation-Annual Grassland | 1 | Great Basin & Intermountain   Ruderal Shrubland | 1
Introduced   Upland Vegetation-Annual Grassland | 1 | Columbia Plateau Steppe and   Grassland | 1
Rocky   Mountain Wetland-Herbaceous | 1 | Rocky Mountain Alpine-Montane   Wet Meadow | 4
Rocky   Mountain Subalpine/Upper Montane Riparian Forest and Woodland | 2 | Northern Rocky Mountain   Dry-Mesic Montane Mixed Conifer Forest | 2

This is the change in suitability for these examples. It looks like they generally stay close, but that's not always the case. We've already shown that the overall suitability does not change that much between 1.4.0 and 2.0.0, so its up to you if you want to dig into this further.

**Comment by philipbaileynar** [comment]
Thanks for the detailed follow through. Closing this issue.
