### ISSUE TITLE
Add mean soil storage capacity Hydrologic Attribute

### ISSUE THREAD

**Issue by tyler1218hatch** [Riverscapes/sqlBRAT#69]
Some Oregon watersheds require an attribute that contains the mean soil storage capacity. I'm not sure exactly how this would be calculated, but the source is the Natural Resources Conservation Service. For more details, look at Appendix F [here](https://pubs.usgs.gov/sir/2005/5116/pdf/sir2005-5116.pdf)

**Comment by philipbaileynar** [comment]
Reassigning this to @tyler1218hatch for the same treatment as #68
