### ISSUE TITLE
Update Layer Files for Risk and Opportunities

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/sqlBRAT#84]
Until recently sqlBRAT had the conservation risk and opportunities data values reversed in the BRAT output ShapeFile. See issue #55 

I have fixed this issue and now the correct values are being written to the correct fields:

* `oPBRC_UI` = Risks (undesirable impacts)
* `oPBRC_UD` = Limitations
* `oPBRC_CR` = Opportunities (conservation and restoration)

Please revisit the layer files and ensure that the symbology for all three layers is correct. I am fairly certain that risks and opportunities are reversed. Meaning that the person who created the layer files followed the values in the data and got the symbology backwards too.

This is a fairly messy task because as soon as you point the symbology to the correct column ArcGIS resets all the symbol classes and you need to rebuild them from scratch.

**Comment by Cashe93** [comment]
Hey @philipbaileynar. It looks like the symbology is correct but the names for the symbology are switched. Does this task simply entail that I change the names of the layer files (oPBRC_CR to oPBRC_UI and vice versa) and then update the business logic?

**Comment by philipbaileynar** [comment]
Yes, that's correct @Cashe93 

But I fear that when you switch the field that the symbology uses, ArcGIS will clear the individual symbols and you will need to start from scratch. Super annoying. Maybe I'm wrong?

Give it a go and let me know how you get on.

**Comment by Cashe93** [comment]
Sounds good @philipbaileynar. I'll give it a go.

**Comment by Cashe93** [comment]
@philipbaileynar it appears to have worked. Let me know if anything needs to be changed.

**Comment by Cashe93** [comment]
@philipbaileynar, scratch that. I see the issue now. Stand by.

**Comment by philipbaileynar** [comment]
Closing issue because this fix was implemented in latest version of RAVE.
